# Generated by Django 3.0.2 on 2020-01-18 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WifiDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bssid', models.CharField(max_length=10)),
                ('ap_ssid', models.CharField(max_length=64)),
            ],
        ),
    ]
