# Generated by Django 3.0.2 on 2020-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifidevice',
            name='vendor',
            field=models.CharField(default='Not Found', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wifidevice',
            name='bssid',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='wifidevice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
