# Generated by Django 2.2.9 on 2020-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_handler', '0003_auto_20200221_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifidevice',
            name='bssid',
            field=models.CharField(max_length=64),
        ),
    ]
