# Generated by Django 2.2.9 on 2020-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_handler', '0004_auto_20200221_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifidevice',
            name='ap_ssid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='wifidevice',
            name='bssid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='wifidevice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wifidevice',
            name='vendor',
            field=models.CharField(max_length=128),
        ),
    ]
