# Generated by Django 2.2.9 on 2020-01-18 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasonic_person_count', '0002_auto_20200112_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bssid', models.CharField(max_length=10)),
                ('ap_ssid', models.CharField(max_length=64)),
            ],
        ),
    ]
